---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  APPS_DIR: "{{.CLUSTER_DIR}}/apps"
  BASE_DIR: "{{.CLUSTER_DIR}}/base"
  CORE_DIR: "{{.CLUSTER_DIR}}/core"
  TZ: "America/Los_Angeles"

includes:
  flux: ./.taskfiles/flux.yaml
  kind: ./.taskfiles/kind.yaml
  lint: ./.taskfiles/lint.yaml

tasks:
  bootstrap:
    desc: Bootstrap the entire cluster
    cmds:
      - task: kind:install
      - task: flux:bootstrap

  lint:
    desc: Lint the files
    cmds:
      - task: lint:yamllint
      - task: lint:markdownlint
      - task: lint:linkcheck
      - task: lint:shellcheck

  default:
    cmds:
      - task -l
    silent: true
