---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  APPS_DIR: "{{.CLUSTER_DIR}}/apps"
  BASE_DIR: "{{.CLUSTER_DIR}}/base"
  CORE_DIR: "{{.CLUSTER_DIR}}/core"
  TZ: "America/Los_Angeles"

tasks:
  bootstrap:
    desc: Bootstrap the entire cluster
    cmds:
      - flux bootstrap github \
          --owner=$GITHUB_USER \
          --repository=kind-cluster \
          --branch=main \
          --path=./cluster/base \
          --personal

  default:
    cmds:
      - task -l
    silent: true
